version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: gql-auth
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"